name: Go build and test

on:
  # If a code is pushed straight into staging we need it to have the same tests as the code pushed via a pr
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  # Check that the code is clean
  # It's done in a separate job as advised by the doc
  # https://github.com/marketplace/actions/run-golangci-lint
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # Checkout to our repository. It allows to run the commands in the rigth place
      - uses: actions/checkout@v3
      # Set up go on environement
      - run: cd back
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      # Check that the code is clean
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      # Checkout to our repository. It allows to run the commands in the rigth place
      - uses: actions/checkout@v3
      - run: cd back
      - run: pwd
      - run: ls
      # Set up go on environement
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      # Check that all the tests of the backend are passed
      - name: Test
        run: go test -v back/...
      # Check that the code build
      - name: Build
        run: go build -v back/...
