name: "js"

on:
  # If a code is pushed straight into staging we need it to have the same tests as the code pushed via a pr
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'ready for test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bunx eslint .
